//------------------------------------------------------------------------------
// <auto-generated>
//     Default.aspx 上の runat="server" コントロールの宣言。
//     .aspx にコントロールを追加した場合は、ここにも同じ ID の宣言を追加するか、
//     プロジェクトを右クリック →「Web アプリケーションに変換」で再生成する。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlmSsoDemo.Web
{
    public partial class Default
    {
        /// <summary>form1 コントロール</summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>phDevWarning コントロール（開発モードの警告）</summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phDevWarning;

        /// <summary>litAuthStatus コントロール（認証状態）</summary>
        protected global::System.Web.UI.WebControls.Literal litAuthStatus;

        /// <summary>litRemoteUser コントロール（REMOTE_USER の値）</summary>
        protected global::System.Web.UI.WebControls.Literal litRemoteUser;

        /// <summary>litShibSession コントロール（Shibboleth セッションの有無）</summary>
        protected global::System.Web.UI.WebControls.Literal litShibSession;

        /// <summary>litLaunch コントロール（SmartClient 起動リンク）</summary>
        protected global::System.Web.UI.WebControls.Literal litLaunch;

        /// <summary>litTicket コントロール（発行した引換券・伏せ字）</summary>
        protected global::System.Web.UI.WebControls.Literal litTicket;

        /// <summary>litTicketLife コントロール（引換券の有効期限）</summary>
        protected global::System.Web.UI.WebControls.Literal litTicketLife;

        /// <summary>litServerVars コントロール（サーバー変数の一覧表）</summary>
        protected global::System.Web.UI.WebControls.Literal litServerVars;
    }
}
