<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Messages\MessageResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>MessageResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Resources\Sql\SqlResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SqlResources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Messages\MessageResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MessageResources.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <CustomToolNamespace>ServiceApi.Resources.Messages</CustomToolNamespace>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Sql\SqlResources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SqlResources.Designer.cs</LastGenOutput>
      <CustomToolNamespace>ServiceApi.Resources.Sql</CustomToolNamespace>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Requests\B1\" />
    <Folder Include="Requests\C1\" />
    <Folder Include="Requests\C2\" />
    <Folder Include="Responses\B1\" />
    <Folder Include="Responses\C2\" />
    <Folder Include="Services\B1\" />
    <Folder Include="Services\C1\" />
    <Folder Include="Services\C2\" />
  </ItemGroup>

</Project>
