# This is a reserved spot for most properties containing passwords or other secrets.
# Created by install at 2026-07-09T08:49:08.752874600Z

# Access to internal AES encryption key
idp.sealer.storePassword =Szlabe5INDTTm5+RLJx1K+4SNxH1kQkH
idp.sealer.keyPassword =Szlabe5INDTTm5+RLJx1K+4SNxH1kQkH

# Password for idp-backchannel.p12 
idp.backchannel.keyStorePassword =7aeEvLvX69X/SB5/tiNsXSc3D0j9QAwb

# Default access to LDAP authn and attribute stores. 
#idp.authn.LDAP.bindDNCredential              =myServicePassword
idp.authn.LDAP.bindDNCredential              = idp-reader
idp.attribute.resolver.LDAP.bindDNCredential =%{idp.authn.LDAP.bindDNCredential:undefined}

# Salt used to generate persistent/pairwise IDs, must be kept secret
#idp.persistentId.salt =changethistosomethingrandom
