//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//
//     このファイルは、Default.aspx 上の runat="server" コントロールを
//     コードビハインドから参照できるようにするための宣言です。
//     通常は Visual Studio が自動生成しますが、.aspx を差し替えた場合は
//     再生成されないことがあるため、内容を明示しています。
//
//     .aspx にコントロールを追加した場合は、ここにも同じ ID の宣言を
//     追加してください（またはプロジェクトを右クリック →
//     「Web アプリケーションに変換」で再生成できます）。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlmSsoDemo.Web
{
    public partial class Default
    {
        /// <summary>
        /// form1 コントロール（&lt;form id="form1" runat="server"&gt;）
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// phDevWarning コントロール（開発モードの警告表示）
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phDevWarning;

        /// <summary>
        /// litAuthStatus コントロール（認証状態）
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAuthStatus;

        /// <summary>
        /// litRemoteUser コントロール（REMOTE_USER の値）
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRemoteUser;

        /// <summary>
        /// litShibSession コントロール（Shibboleth セッションの有無）
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litShibSession;

        /// <summary>
        /// litServerVars コントロール（サーバー変数の一覧表）
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litServerVars;
    }
}
