//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceApi.Resources.Sql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceApi.Resources.Sql.SqlResources", typeof(SqlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT :VAL + 1 ID, &apos;&lt;A1Service&gt; TESTDATA1&apos; DATANAME FROM DUAL 
        ///UNION 
        ///SELECT :VAL + 2 ID, &apos;&lt;A1Service&gt; TESTDATA2&apos; DATANAME FROM DUAL .
        /// </summary>
        internal static string SQL_A1_001 {
            get {
                return ResourceManager.GetString("SQL_A1_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT EMPNO, ENAME, JOB, MGR, 
        ///TO_CHAR(HIREDATE, &apos;yyyy/mm/dd&apos;) HIREDATE, 
        ///SAL, COMM, DEPTNO 
        ///FROM EMP 
        ///WHERE DEPTNO = :DEPTNO 
        ///ORDER BY EMPNO.
        /// </summary>
        internal static string SQL_B1_001 {
            get {
                return ResourceManager.GetString("SQL_B1_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT d.DEPTNO, d.DNAME, e.EMPNO, e.ENAME 
        ///FROM DEPT d 
        ///INNER JOIN EMP e 
        ///ON e.DEPTNO = d.DEPTNO 
        ///ORDER BY d.DEPTNO, e.EMPNO .
        /// </summary>
        internal static string SQL_C1_001 {
            get {
                return ResourceManager.GetString("SQL_C1_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT d.DEPTNO DEPTNO, d.DNAME DNAME, 
        ///e1.EMPNO MEMBER_EMPNO, e1.ENAME MEMBER_ENAME, 
        ///e2.EMPNO STAFF_EMPNO, e2.ENAME STAFF_ENAME 
        ///FROM DEPT d 
        ///INNER JOIN EMP e1 ON e1.DEPTNO = d.DEPTNO 
        ///INNER JOIN EMP e2 ON e2.MGR = e1.EMPNO 
        ///ORDER BY d.DEPTNO, e1.EMPNO, e2.EMPNO.
        /// </summary>
        internal static string SQL_C2_001 {
            get {
                return ResourceManager.GetString("SQL_C2_001", resourceCulture);
            }
        }
    }
}
